name: Dependency Caching

on: [push]

jobs:
  build_with_caching:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      # 1. Setup Cache Step (ID is used for logic, Name is descriptive)
      #    REQUIRED KEY: cache-8bbf611
      - name: Setup Cache using Key cache-8bbf611 
        id: cache-dependencies  # <-- Unique ID used to reference outputs
        uses: actions/cache@v4
        with:
          path: node_modules
          key: cache-8bbf611
          
      # 2. Install Dependencies (Runs only on cache MISS)
      - name: Install dependencies (if cache missed)
        if: steps.cache-dependencies.outputs.cache-hit != 'true'
        run: |
          echo "Simulating dependency installation..."
          mkdir node_modules
          echo "Dependencies installed successfully." 

      # 3. REQUIRED ECHO STEP: Prints the cache hit/miss result
      #    REQUIRED NAME: prime-cache-8bbf611
      - name: prime-cache-8bbf611
        run: |
          CACHE_RESULT="${{ steps.cache-dependencies.outputs.cache-hit }}"
          if [ "$CACHE_RESULT" = "true" ]; then
            echo "✅ Cache Status: HIT (Dependencies skipped)"
          else
            echo "❌ Cache Status: MISS (Dependencies installed and saved)"
          fi
          echo "Cache hit output: ${{ steps.cache-dependencies.outputs.cache-hit }}"
